defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: root
  password: 
  host: localhost

development:
  database: crossgate
  <<: *defaults

test:
  database: crossgate_test
  <<: *defaults

production:
  database: crossgate
  <<: *defaults